### ISSUE TITLE
最后的functionBody字符串里面会有多余的tpl+=''，虽然不影响，但是能否去掉？

### ISSUE THREAD

**Issue by fantasy525** [Away0x/learning-template#1]
`var tpl='    ' ; if( data.con > 20 ) {  tpl += '        <p>ifififififif</p>    ' ; } else {  tpl += '        <p>elseelseelseelse</p>    ' ; }  tpl += '    ' ; for(var i = 0; i < data.list.length; i++) {  tpl += '    	<p>'+(i )+' : '+( data.list[i] )+'</p>    ' ; }  tpl += ''; return tpl;`
比如在else 的{}末尾的}之后应该不用再tpl+=‘’了吧，因为他后面没有html文本了

**Comment by Away0x** [comment]
tpl += '  这个是为了加上结尾的一个引号哟，否则引号不闭合，会报错的。
